### ISSUE TITLE
예상 완성 일은 언제인가요?

### ISSUE THREAD

**Issue by LeeHeoJae** [Su-Yong/KakaoBot#1]

**Comment by Su-Yong** [comment]
저의 작업속도를 본다면... 게을러 터졌기 때문에 2월 중반쯤 되어 보입니다

**Comment by LeeHeoJae** [comment]
히익....

**Comment by LeeHeoJae** [comment]
소스 보니 html 을 응용이랄까 뭐 해서 만드신거같은데 api 불러오는게 가능할까요?

**Comment by Su-Yong** [comment]
HTML은 그저 알림받은 메세지형이 HTML형이여서 그렇습니다 (그룹일때만) 원래 원리는 알림 엑세스 입니다

**Comment by LeeHeoJae** [comment]
완성도는 약 몇퍼인가요?

**Comment by Su-Yong** [comment]
현재 계획중인 기능의 70%가 구현되었습니다.

https://play.google.com/store/apps/details?id=com.suyong.kakaobot

에 업데이트 될겁니다

**Comment by LeeHeoJae** [comment]
1.1 버전은 이제 사용 가능한건가요?

2017. 2. 17. 오후 1:57에 "SuYong" <notifications@github.com>님이 작성:

**Comment by Su-Yong** [comment]
현재 1.1버전은 업로드 되지 않았습니다. 1.0.2 버전이 업로드 되었습니다.

**Comment by LeeHeoJae** [comment]
그렇군요.

근데 처음 액티비티에서 사용하는 방법을 모르겠네요..

2017. 2. 17. 오후 7:42에 "SuYong" <notifications@github.com>님이 작성:
